/**
 README.md create-website-handler.js create-website.js migrate_to_unified_db.sh modified_create_website.js modified_create_website.yml node_modules package-lock.json package.json register-site.js registration.log restore-data.js restore.html teacher unified_data_readme.md unified_script_example.js unified_site_data.js unified_site_data_schema.sql site-config.js
 README.md create-website-handler.js create-website.js migrate_to_unified_db.sh modified_create_website.js modified_create_website.yml node_modules package-lock.json package.json register-site.js registration.log restore-data.js restore.html teacher unified_data_readme.md unified_script_example.js unified_site_data.js unified_site_data_schema.sql This file contains configuration specific to this website instance.
 README.md create-website-handler.js create-website.js migrate_to_unified_db.sh modified_create_website.js modified_create_website.yml node_modules package-lock.json package.json register-site.js registration.log restore-data.js restore.html teacher unified_data_readme.md unified_script_example.js unified_site_data.js unified_site_data_schema.sql It is automatically generated by GitHub Actions on: 2025-04-11T21:49:30.627Z
 */

const siteConfig = {
 // Website ID from the database
 websiteId: "3",

 // Site name
 siteName: "Ahmed Mahmoud",

 // Site URL
 siteUrl: "https://portflyo-new.vercel.app/teacher/ahmeddd/index.html",

 // Folder name
 folderName: "ahmeddd",

 // Created timestamp
 createdAt: "2025-04-11T21:49:28.858929+00:00"
};

export default siteConfig;
