/**
 README.md create-website-handler.js create-website.js node_modules package-lock.json package.json register-site.js registration.log restore-data.js restore.html teacher site-config.js
 README.md create-website-handler.js create-website.js node_modules package-lock.json package.json register-site.js registration.log restore-data.js restore.html teacher This file contains configuration specific to this website instance.
 README.md create-website-handler.js create-website.js node_modules package-lock.json package.json register-site.js registration.log restore-data.js restore.html teacher It is automatically generated by GitHub Actions on: 2025-04-10T14:27:57.153Z
 */

const siteConfig = {
 // Website ID from the database
 websiteId: "ahmed_01",

 // Site name
 siteName: "Ahmed Mahmoud",

 // Site URL
 siteUrl: "https://portflyo-new.vercel.app/teacher/ahmed/index.html",

 // Folder name
 folderName: "ahmed",

 // Created timestamp
 createdAt: "2025-04-10T14:27:55.783576+00:00"
};

export default siteConfig;
