/**
 README.md node_modules package-lock.json package.json register-site.js registration.log restore-data.js restore.html teacher site-config.js
 README.md node_modules package-lock.json package.json register-site.js registration.log restore-data.js restore.html teacher This file contains configuration specific to this website instance.
 README.md node_modules package-lock.json package.json register-site.js registration.log restore-data.js restore.html teacher It is automatically generated by GitHub Actions on: 2025-04-01T11:36:57.156Z
 */

const siteConfig = {
 // Website ID from the database
 websiteId: "2637a621-781a-4e16-9ef6-7bba3ef29278",

 // Site name
 siteName: "Ahmed Mahmoud",

 // Site URL
 siteUrl: "https://portflyo-new.vercel.app/teacher/ahmed_mahmoud/index.html",

 // Folder name
 folderName: "ahmed_mahmoud",

 // Created timestamp
 createdAt: "2025-04-01T11:36:55.525365+00:00"
};

export default siteConfig;
